# Generated by Django 5.0.7 on 2024-08-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_firstname', models.CharField(max_length=80)),
                ('customer_lastname', models.CharField(max_length=80)),
                ('customer_org', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_category', models.CharField(max_length=200)),
                ('product_description', models.CharField(max_length=1000)),
                ('date_released', models.DateTimeField(verbose_name='date released')),
            ],
        ),
    ]
